# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Softbody_Simulation_config = debug

else ifeq ($(config),release)
  Softbody_Simulation_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Softbody\ Simulation

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Softbody\ Simulation:
ifneq (,$(Softbody_Simulation_config))
	@echo "==== Building Softbody Simulation ($(Softbody_Simulation_config)) ===="
	@${MAKE} --no-print-directory -C build/SoftbodySimulation -f Makefile config=$(Softbody_Simulation_config)
endif

clean:
	@${MAKE} --no-print-directory -C build/SoftbodySimulation -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Softbody Simulation"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"